query session {
  getSession {
    id
    adminUserId
    adminUserEmail
    impersonable
    impersonate {
      storeUserId
      storeUserEmail
    }
    profile {
      firstName
      lastName
      document
      phone
    }
  }
}
