query session {
  getSession {
    id
    adminUserId
    impersonable
    adminUserEmail
    impersonate {
      profile {
        phone
        email
        lastName
        document
        firstName
      }
    }
  }
}
